export const ActionTypes = {
  // Empty Fields
  EMPTYFIELDS: "EMPTYFIELDS",
  //user
  HANDLE_USER_DATA: "HANDLE_USER_DATA",
  HANDLE_USER_RESET: "HANDLE_USER_RESET",
  GET_ALL_USERS: "GET_ALL_USERS",
  SET_EDIT_USER: "SET_EDIT_USER",
  SET_EDIT: "SET_EDIT",
  SET_SELECTED_USER: "SET_SELECTED_USER",
  ADD_USERS: "ADD_USERS",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
};
